# This is a basic workflow to help you get started with Actions

name: Deploy to EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_AWS }}
          username: ${{ secrets.USERNAME_AWS }}
          key: ${{ secrets.KEY_AWS }}
          script: |
            sudo docker pull kobulwidodo/go-simple-api:latest
            sudo docker stop go-app
            sudo docker rm go-app
            sudo docker container create --name go-app -p 8080:8080 kobulwidodo/go-simple-api
            sudo docker container start go-app
